#!/bin/bash
# Credits: @mrismanaziz & @excute7
# Copyright (C) 2022 Pyro-HyperUserbot
#
# This file is a part of < https://github.com/Ling-ex/Hyper/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/Ling-ex/Hyper/blob/main/LICENSE/>.
#
# t.me/SharingUserbot & t.me/Lunatic0de
# t.me/HyperSupportQ & t.me/storyQi

# start
python3 -m ProjectMan
